### ISSUE TITLE
[Bug] Banlist Append creates a banlist only from the ydk file 

### ISSUE THREAD

**Issue by Milkamilk** [IasonNautica/betterPackOpener#3]
The Banlist Append function is broken. It only creates a banlist out of the ydk file and gets rid of the first banlist. In my example below, I created a whitelist from Legend of Blue Eyes White Dragon and appended my pulls from Metal Raiders to it.

![Blue-Eyes](https://user-images.githubusercontent.com/91711702/135735824-ea481ec0-d2c5-47c5-870e-2e2a8656a4b5.png)
This is the original banlist created from only Legend of Blue Eyes White Dragon. Here you can see that I pulled 2 Blue-Eyes White Dragon.

![AppendBlueEyes](https://user-images.githubusercontent.com/91711702/135735847-d6447650-c29a-412a-b134-dff993373976.png)
Here I attempt to search for Blue-Eyes from the appended whitelist. As you can see, Blue-Eyes is nowhere to be found.

![MetalRaiders](https://user-images.githubusercontent.com/91711702/135735899-cc7530fa-636a-442a-9129-fb0488bd34cd.PNG)
If I clear my search bar, only cards from Metal Raiders are visible.

Here is my LOB whitelist as well as the appended whitelist as .txt files.
[LOBWhitelist.txt](https://github.com/IasonNautica/betterPackOpener/files/7272497/LOBWhitelist.txt)
[AppendedList.txt](https://github.com/IasonNautica/betterPackOpener/files/7272498/AppendedList.txt)

My process for appending the list was first selecting LOB and generating a pull ydk. Next I created a whitelist using the create whitelist function. Afterwards I selected Metal Raiders and generated a pull. Finally I used Banlist Append, selecting the whitelist created from LOB and the Metal Raiders ydk file.

**Comment by IasonNautica** [comment]
Hey, thanks for the heads up. This was caused due to some shitty variable naming inside the main function, I've fixed it and will push it to main now. 
I will make a new release with both of your reports accounted for in a bit
